stage:
- build
- Build Docker image
- deploy

build:
- maven:
    goal: clean package

Build Docker image:
- docker:
  - docker build -t private-docker-registry:5000/bluegreen:0.0.1 . &&
  - docker images &&
#  - docker login ${} -u ${} -p${}
  - docker push private-docker-registry:5000/bluegreen:0.0.1

#deploy:
#- kubectl:
#  - kubectl apply -n helm -f ./k8s/deploy.yaml
#  - kubectl apply -n helm -f ./k8s/service.yaml

agent:
  profile: [maven, docker, kubectl]
  volumes:
  - persistentVolumeClaim:
      claimName: slave-workspace
      mountPath: /root/.m2/repository
      readOnly: false
