stage:
- Build (Maven)
- Build (Docker)
- Deploy (Kubernetes)

Build (Maven):
- maven:
    goal: clean package
    options: -Dmaven.test.skip=true -V

Build (Docker):
- docker.build:
    tag: $image
- docker.push:
    imageName: $image
    credentialId: docker-hub-hoon

Deploy (Kubernetes):
- kubectl.delete:
    file: k8s
- kubectl.apply:
    file: k8s
    namespace: $ns

agent:
  profile: [maven, docker, kubectl]
  volumes:
  - pvc:test-maven-repo-pvc: /root/.m2/repository
    readOnly: false

env:
  image: yoon5/bluegreen:$version
  version: 0.0.2
  ns: helm
