stage:
- build
- Build Docker image
- deploy

build:
- maven:  #mvn clean package -Dmaven.test.skip=true
    goal: ${maven.goal}
    options: -Dmaven.test.skip=${maven.test.skip} -X
#   options: ${maven.options}
#   options: ${maven.options.join(' ')}

Build Docker image:
- docker:
  - docker build -t $image .
  - docker images
#  - docker login -u *** -p ***
#  - docker push $image

deploy:
- kubectl:
  - kubectl apply -n $ns -f ./k8s

agent:
  profile: [maven, docker, kubectl]
#  volumes:
#  - pvc/slave-workspace: /root/.m2/repository
#    readOnly: false
#  volumes:
#  - persistentVolumeClaim:
#      claimName: test-maven-repo-pvc
#      mountPath: /root/.m2/repository
#      readOnly: false

env:
  image: yoon5/bluegreen:$version
  version: 0.0.2
  ns: test-jenkins-app
  maven:
    goal: clean package
#   options: -Dmaven.test.skip=${maven.test.skip} -X
#   options: [-Dmaven.test.skip=${maven.test.skip}, -X]
    test:
      skip: true
