stage:
- build
- Build Docker image
- deploy

build:
- maven: mvn clean package -Dmaven.test.skip=true

Build Docker image:
- docker:
  - docker build -t $image .
  - docker images
#  - docker login -u *** -p ***
#  - docker push $image

deploy:
- kubectl:
  - kubectl apply -f ./k8s/deploy.yaml || kubectl create -f ./k8s/deploy.yaml
  - kubectl apply -f ./k8s/service.yaml

agent:
  profile: [maven, docker, kubectl]
  namespace: helm
#  volumes:
#  - pvc/slave-workspace: /root/.m2/repository
#    readOnly: false
  volumes:
  - persistentVolumeClaim:
      claimName: test-maven-repo-pvc
      mountPath: /root/.m2/repository
      readOnly: false

env:
  image: yoon5/bluegreen:$version
  version: 0.0.2
  ns: helm
