stage:
- build
- Build Docker image
- deploy

build:
- maven:
    goal: clean package
    options: -Dmaven.test.skip=true -V

Build Docker image:
- docker.build:
    tag: $image
- docker.push:
    credentialId: docker-hub-hoon

deploy:
- kubectl:
  - kubectl apply -n $ns -f ./k8s

agent:
  profile: [maven, docker, kubectl]
  volumes:
  - pvc:test-maven-repo-pvc: /root/.m2/repository
    readOnly: false

env:
  image: yoon5/bluegreen:$version
  version: 0.0.2
  ns: helm
