## Defind Pipeline Stages
stage:
- Build (Maven)
- Build (Docker)
- Deploy (Kubernetes)

## Configure Steps of each stage
Build (Maven):
- maven:
    goal: clean package
    options: -Dmaven.test.skip=true -V

Build (Docker):
- docker.build:
    tag: $image
- docker.push:
    imageName: $image
    credentialId: docker-hub-hoon

Deploy (Kubernetes):
- kubectl.apply:
    file: k8s
    folder: k8s
    #namespace: $ns

## Create dynamic slave running on Kubernetes
agent:
  profile: [maven, docker, kubectl]
  volumes:
  - pvc:test-maven-repo-pvc: /root/.m2/repository
    readOnly: false

## Defind reusable variables in method arguments and shell script
env:
  image: yoon5/bluegreen:$version
  version: 0.0.2
  ns: helm
