stage:
- build
- Build Docker image
- deploy

build:
- maven: mvn clean package -Dmaven.test.skip=true

Build Docker image:
- docker:
#  - docker login -u *** -p ***
  - docker build -t $image .
  - docker images
#  - docker push yoon5/bluegreen:0.0.2
#  - docker build -t private-docker-registry:5000/bluegreen:0.0.1 . &&
#  - docker push private-docker-registry:5000/bluegreen:0.0.1

deploy:
- kubectl:
  - kubectl apply -n $ns -f ./k8s/deploy.yaml
  - kubectl apply -n $ns -f ./k8s/service.yaml

agent:
  profile: [maven, docker, kubectl]
  volumes:
  - persistentVolumeClaim:
      claimName: slave-workspace
      mountPath: /root/.m2/repository
      readOnly: false

env:
  image: yoon5/bluegreen:$version
  version: 0.0.3
  ns: helm
