@Library('sail-lib@hoon') _

def builder = new ContainerBuilder(this)
def config = """
profile:[maven, docker, kubectl]
volumes:
- empty:                  /root/.m2/repository    # https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/EmptyDirVolume.java#L48
  memory:   true
- pvc:slave-workspace:    /root/volume/pvc        # https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/PersistentVolumeClaim.java#L45
  readOnly: true
- configmap:xxxx:         /root/volume/configmap  # https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/ConfigMapVolume.java#L41
  readOnly: true
- nfs:slave-workspace:    /root/volume/nfs        # https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/NfsVolume.java#L46
  readOnly: true
- secret:slave-workspace: /root/volume/secret     # https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/SecretVolume.java#L41
- host:/mnt/test-volume:  /root/volume/host       #https://github.com/jenkinsci/kubernetes-plugin/blob/master/src/main/java/org/csanchez/jenkins/plugins/kubernetes/volumes/HostPathVolume.java#L40
  readOnly: true
"""

println builder.extend(config).build()
