apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: bluegreen-0.0.1
  labels:
    app: bluegreen
    version: 0.0.1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: bluegreen
      version: 0.0.1
  template:
    metadata:
      labels:
        app: bluegreen
        version: 0.0.1
    spec:
      containers:
      - name: bluegreen
        image: private-docker-registry:5000/bluegreen:0.0.1
        ports:
        - containerPort: 8080
        imagePullPolicy: Always
  strategy:
    type: RollingUpdate
