stage:
- build
- Build Docker image
- deploy

build:
- maven:
    goal: ${maven.goal}
    options: -Dmaven.test.skip=${maven.test.skip} -V

Build Docker image:
- docker:
  - docker build -t $image .

deploy:
- kubectl:
  - kubectl apply -n $ns -f ./k8s

agent:
  profile: [maven, docker, kubectl]
  serviceAccount: zcp-jenkins
  volumes:
  - persistentVolumeClaim:
      claimName: zcp-jenkins-mvn-repo
      mountPath: /root/.m2/repository
      readOnly: false

env:
  image: yoon5/bluegreen:$version
  version: 0.0.2
  maven:
    goal: clean package
    test:
      skip: true
