stage: [Build Maven, Build Docker Image, Deploy to k8s]

Build Maven:
- maven: mvn clean package ${maven.options}

Build Docker Image:
- docker: docker build -t $image .
#  - docker login -u *** -p ***
#  - docker push $image

Deploy to k8s:
- kubectl: kubectl apply -n $ns -f ./k8s

agent:
  profile: [maven, docker, kubectl]
  volumes:
  - persistentVolumeClaim:
      claimName: test-maven-repo-pvc
      mountPath: /root/.m2/repository
      readOnly: false

env:
  ns: helm
  image: yoon5/bluegreen:0.0.2
  maven:
    options: -Dmaven.test.skip=true -V
